# These all have to run to be considered a good build. They do at the time of this comment.
# We always mistakenly leave a feature flag after development. So when the pre commit hook runs, it often gives
# false positive if we don't use --no-default-features flag when testing.
# [alias]
# server = "build -q --bin server --no-default-features --features native"
# run-server = "run -q --bin server --no-default-features --features=native"
# run-native = "run -q --bin native --no-default-features --features native"

# # No build. The Wasm is run with other server.
# web = "build -q --bin web --no-default-features --features web --target wasm32-unknown-unknown"
# trunk = "trunk build -q --release"
# trunk-run = "trunk serve src/web/public/index.html --features web"

[alias]
# ─────────────────────────────────────────────
# Lints
# Fix lint issues
# ─────────────────────────────────────────────
fix-all-web = "fix --bin web --no-default-features --features web --target wasm32-unknown-unknown --allow-dirty"
fix-all-native = "fix --bin native --no-default-features --features native --allow-dirty"

# ─────────────────────────────────────────────
# Builds
# Create builds of specific binaries
# ─────────────────────────────────────────────
web = "build --bin web --no-default-features --target wasm32-unknown-unknown --features web"
server = "build --bin server --no-default-features --features native"
native = "build --bin native --no-default-features --features native"

# ─────────────────────────────────────────────
# Direct execution
# ─────────────────────────────────────────────

run-native = "run --bin native --no-default-features --features native"
run-server = "run --bin server --no-default-features --features native"
run-daemon = [
  "run",
  "-q",
  "--bin",
  "native",
  "--no-default-features",
  "--features",
  "native,daemon",
]

# ─────────────────────────────────────────────
# Daemon
# ─────────────────────────────────────────────

daemon = "run -q --bin native --no-default-features --features native -- start"
daemon-bg = "run -q --bin native --no-default-features --features native -- start"
daemon-fg = "run -q --bin native --no-default-features --features native -- start --tail=true"


# ─────────────────────────────────────────────
# Tray
# ─────────────────────────────────────────────

tray = "run -q --bin native --no-default-features --features native -- tray"
tray-bg = "run -q --bin native --no-default-features --features native -- tray --tail=false"
tray-fg = "run -q --bin native --no-default-features --features native -- tray --tail=true"


# ─────────────────────────────────────────────
# Window
# ─────────────────────────────────────────────

window = "run -q --bin native --no-default-features --features native -- window"
window-bg = "run -q --bin native --no-default-features --features native -- window --tail=false"
window-fg = "run -q --bin native --no-default-features --features native -- window --tail=true"

# ─────────────────────────────────────────────
# CLI commands
# ─────────────────────────────────────────────

status = "run -q --bin native --no-default-features --features native -- status"
doctor = "run -q --bin native --no-default-features --features native -- doctor"
metrics = "run -q --bin native --no-default-features --features native -- metrics"
format = "run -q --bin native --no-default-features --features native -- format"

# ─────────────────────────────────────────────
# Web
# ─────────────────────────────────────────────

trunk = "trunk build -q --release"
trunk-run = "trunk serve src/web/public/index.html --features web"
# trunk-it = "cargo build --bin web --target wasm32-unknown-unknown --features web && trunk serve src/web/public/index.html "

[term]
quiet = true                    # whether cargo output is quiet
verbose = false                  # whether cargo provides verbose output
color = 'auto'                   # whether cargo colorizes output
hyperlinks = true                # whether cargo inserts links into output
unicode = true                   # whether cargo can render output using non-ASCII unicode characters
progress.when = 'auto'           # whether cargo shows progress bar
progress.width = 80              # width of progress bar
progress.term-integration = true # whether cargo reports progress to terminal emulator
