[alias]
server = "build --bin server --no-default-features --features native"
native = "run --bin native --no-default-features --features native"
web = "build --bin web --no-default-features --features web --target wasm32-unknown-unknown"
web-run = "run --bin web --no-default-features --target wasm32-unknown-unknown --features web"
trunk-build = "trunk build --release"
trunk-run = "trunk serve src/web/public/index.html --features web"
