syntax = "proto3";

package leetcode;

import "type.proto";

service ProblemService {
  rpc CreateProblem(leetcode.types.CreateProblemRequest) returns (leetcode.types.Problem);
  rpc GetProblem(leetcode.types.GetProblemRequest) returns (leetcode.types.Problem);
  rpc UpdateProblem(leetcode.types.UpdateProblemRequest) returns (leetcode.types.Problem);
  rpc DeleteProblem(leetcode.types.DeleteProblemRequest) returns (leetcode.types.Empty);

  rpc ListProblems(leetcode.types.ListProblemsRequest) returns (leetcode.types.ListProblemsResponse);
}

service SubmissionService {
  rpc CreateSubmission(leetcode.types.CreateSubmissionRequest)
      returns (leetcode.types.Submission);

  rpc GetSubmission(leetcode.types.GetSubmissionRequest)
      returns (leetcode.types.Submission);

  rpc UpdateSubmission(leetcode.types.UpdateSubmissionRequest)
      returns (leetcode.types.Submission);

  rpc DeleteSubmission(leetcode.types.DeleteSubmissionRequest)
      returns (leetcode.types.Empty);

  rpc ListSubmissions(leetcode.types.ListSubmissionsRequest)
      returns (leetcode.types.ListSubmissionsResponse);

  // Convenience operations
  rpc RunSubmission(leetcode.types.RunSubmissionRequest)
      returns (leetcode.types.Submission);
}

// service FavoriteService {
//   rpc CreateFavorite(CreateFavoriteRequest) returns (Favorite);
//   rpc GetFavorite(GetFavoriteRequest) returns (Favorite);
//   rpc DeleteFavorite(DeleteFavoriteRequest) returns (Empty);
//   rpc ListFavorites(ListFavoritesRequest) returns (ListFavoritesResponse);
// }

// message Favorite {
//   string id = 1;
//   string user_id = 2;
//   string problem_id = 3;
//   google.protobuf.Timestamp created_at = 4;
// }
